# docker-compose.yml
services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: mecanumbot_camera:humble
    container_name: mecanumbot_camera_ros2
    working_dir: /ws
    stdin_open: true
    tty: true
    # Mount the current workspace under /ws
    volumes:
      - ./mecanumbot_camera:/ws/mecanumbot_camera
      - ./mecanumbot_camera/models:/ws/mecanumbot_camera/models
      - ./mecanumbot_camera/media:/ws/mecanumbot_camera/media:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # Linux X11
    environment:
      # Adjust the domain ID if you share the network with other ROS graphs.
      - ROS_DOMAIN_ID=0
      # For GUI forwarding (WSLg / X11) set the display variables.
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    ports:
      - "8765:8765"
    command: bash


