# docker-compose.yml
services:
  ros2:
    image: osrf/ros:humble-desktop
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: creativecamera_ros2
    working_dir: /ws
    stdin_open: true
    tty: true
    # A jelenlegi mappát csatoljuk be /ws alá
    volumes:
      - ./ros2_ws:/ws/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # Linux X11
    environment:
      # Ha több ROS rendszered van a hálózaton, állíts külön domain ID-t (pl. 42).
      - ROS_DOMAIN_ID=0
      # Ha GUI-t is szeretnél később (WSLg / X11), majd tedd hozzá:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    ports:
      - "8765:8765"
    command: bash
